name: VitenWahl
favicon: null
layout_spectrum: 0.4851624071598053
typography_spectrum: 0.3296118408907205
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.00930818822234869
  lightness: 0.17445752816274762
  saturation: 0.7957036816515028
  rhythmicContrast: 0.8760772047098726
purpose: []
